{
 "title": "Spring Boot Statistics",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "数据源", "query": "prometheus" },
   { "name": "Application", "label": "应用", "query": { "query": "label_values(application)" } },
   {
    "name": "Service",
    "label": "微服务",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$Application\"}, service)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_count{application=~\"$Application\",service=~\"$Service\"},pod)"
    }
   },
   {
    "name": "Area",
    "label": "堆类型",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$Application\", service=\"$Service\"},area)"
    }
   },
   {
    "name": "Id",
    "label": "内存池(堆)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$Application\", service=\"$Service\",area=\"$Area\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$Application\", service =\"$Service\",pod=\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$Application\", service =\"$Service\", pod!=\"$Pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$Application\", service =\"$Service\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$Application\", service=\"$Service\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$Application\",service=\"$Service\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_max_files{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "Open Files Pod: $Pod"
    },
    {
     "expr": "process_files_max_files{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "Max Files Pod: $Pod"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$Application\", service =\"$Service\",pod=\"$Pod\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$Application\", service =\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "System CPU Usage {{pod}}"
    },
    {
     "expr": "process_cpu_usage{application=\"$Application\", service =\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "Process CPU Usage {{pod}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$Application\", service =\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "Load Average [1m] {{pod}}"
    },
    {
     "expr": "system_cpu_count{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "CPU Core Size {{pod}}"
    }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "微服务: $Service 堆类型: $Area 内存池: $Id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$Application\", service=\"$Service\", pod=\"$Pod\", area=\"$Area\", id=~\"$Id\"}",
     "legendFormat": "Used {{pod}} 内存池: {{id}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$Application\",service=\"$Service\", pod=\"$Pod\", area=\"$Area\", id=~\"$Id\"}",
     "legendFormat": "Commited {{pod}}  内存池: {{id}}"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$Application\", service=\"$Service\", pod=\"$Pod\", area=\"$Area\", id=~\"$Id\"}",
     "legendFormat": "Max {{pod}}  内存池: {{id}}"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "Classes Loaded {{pod}}"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}[5m])",
     "legendFormat": "Classes Unloaded {{pod}}"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\", id=\"direct\"}",
     "legendFormat": "Used Bytes {{pod}}"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes {{pod}}"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\", id=\"mapped\"}",
     "legendFormat": "Used Bytes {{pod}}"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes {{pod}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "Daemon {{pod}}"
    },
    {
     "expr": "jvm_threads_live_threads{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "Live {{pod}}"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}",
     "legendFormat": "Peak {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote 5分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}[5m])",
     "legendFormat": "allocated {{pod}}"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}[5m])",
     "legendFormat": "promoted {{pod}}"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "GC Count 5分钟",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}] {{pod}}"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration 5分钟",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{application=\"$Application\", service=\"$Service\", pod=~\"$Pod\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}] {{pod}}d\""
    }
   ]
  }
 ]
}